spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    open-in-view: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_NAME:teens}?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&useUnicode=true&connectionCollation=utf8mb4_general_ci
    username: root
    password: ${PASSWORD}

  messages:
    basename: classpath:messages
    encoding: UTF-8

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

server:
  port: ${PORT:8080}

sentry:
  dsn: ${SENTRY_DSN}
  send-default-pii: true
  environment: development

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    s3:
      bucket: ${BUCKET_NAME}
      exp-time: 604800000
    region:
      static: ${AWS_STATIC}
    stack:
      auto: false