spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    open-in-view: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_NAME:teens}?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&useUnicode=true&connectionCollation=utf8mb4_general_ci
    username: root
    password: ${PASSWORD}

server:
  port: ${PORT:8080}

sentry:
  dsn: https://96dd077b9f9e14658fa035a51aeeed32@o4510303685902336.ingest.us.sentry.io/4510497320468480
  send-default-pii: true
  environment: development